[main]
font=JetBrainsMono Nerd Font:size=16
terminal=kitty
prompt=>
icon-theme=Adwaita
icons-enabled=yes
width=40
lines=12
horizontal-pad=20
vertical-pad=10
inner-pad=5

[colors]
# Tokyo Night
background=1a1b26dd
text=c0caf5ff
match=7dcfffff
selection=33467cff
selection-text=ffffffff
selection-match=89ddffff
border=7aa2f7cc

[border]
width=2
radius=4
