background {
    path = /home/michal/.config/hypr/wallpapers/cyberpunk1.jpg
}

shape {
    size = 320, 120
    position = 0, 150

    halign = center
    valign = center

    color = rgba(0b0b12dd)

    rounding = 20
}

label {
    text = cmd[update:1000] echo "$(date +"%H:%M")"

    font_size = 72
    color = rgb(ffc857)

    shadow_passes = 3
    shadow_size = 4
    shadow_color = rgb(000000)

    position = 0, 150
    halign = center
    valign = center
}

input-field {
    size = 320, 50
    position = 0, -100

    halign = center
    valign = center

    rounding = 6

    outer_color = rgb(ffc857)
    inner_color = rgb(0b0b12)

    font_color = rgb(fff1c1)

    outline_thickness = 2

    dots_center = true
    fade_on_empty = false

    check_color = rgb(00e5ff)
    fail_color = rgb(ff2a9d)
}
