background {
    path = /home/michal/.config/hypr/wallpapers/osaka-jade-bg.jpg
}

# ─────────────────────────────────────────
# CLOCK PANEL
# ─────────────────────────────────────────

shape {
    size = 320, 120
    position = 0, 350

    halign = center
    valign = center

    color = rgba(050f0cdd)

    rounding = 16
}

label {
    text = cmd[update:1000] echo "$(date +'%H:%M')"

    font_size = 86
    color = rgb(b8ffd9)

    position = 0, 350

    halign = center
    valign = center

    shadow_passes = 3
    shadow_size = 5
    shadow_color = rgba(000000aa)
}

# ─────────────────────────────────────────
# PASSWORD FIELD
# ─────────────────────────────────────────

input-field {
    size = 420, 64

    position = 0, -130

    halign = center
    valign = center

    rounding = 18

    outer_color = rgb(39d98a)
    inner_color = rgba(050f0cee)

    font_color = rgb(d8ffe8)

    outline_thickness = 2

    dots_center = true
    fade_on_empty = false

    check_color = rgb(39d98a)
    fail_color = rgb(ff4f81)
}
